apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-backendwithfront
  namespace: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend-test
  template:
    metadata:
      labels:
        app: backend-test
    spec:
      containers:
      - image: registry.digitalocean.com/swipebay-registry/backend:0f1c4ca 
        name: backend-test
        ports:
           - containerPort: 3000     
        envFrom:
          - secretRef:
             name: backend-secrets 
    
