apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring   
spec:
  selector:
    matchLabels:
      app: backend-test  
  namespaceSelector:
    matchNames:
      - backend         
  endpoints:
    - targetPort: 3000
      path: /metrics     
      interval: 15s      
      scrapeTimeout: 10s
      scheme: http

