name: Frontend CI & Snyk Scan

on:
  push:
    branches:
      - "*"
    paths:
      - "app/**"
      - "components/**"
      - "hooks/**"
      - "lib/**"
      - "config/**"
      - "context/**"
      - "messages/**"
      - "schema/**"
      - "store/**"
      - "types/**"
      - "next.config.ts"
      - "package.json"
      - "bun.lockb"
      - "Dockerfile"
  pull_request:
    branches:
      - main
    paths:
      - "app/**"
      - "components/**"
      - "hooks/**"
      - "lib/**"
      - "config/**"
      - "context/**"
      - "messages/**"
      - "schema/**"
      - "store/**"
      - "types/**"
      - "next.config.ts"
      - "package.json"
      - "bun.lockb"
      - "Dockerfile"
  workflow_dispatch:

jobs:
  build-test:
    name: Build & Test (Frontend)
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build project
        run: bun run build

      - name: Run tests
        run: bun run test || echo "No tests found"

      - name: Notify Slack (Build/Test Success)
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\":white_check_mark: *Frontend CI Succeeded!* ✅\n• Repo: *${{ github.repository }}*\n• Branch: *${{ github.ref_name }}*\n• Actor: *${{ github.actor }}*\n• Run: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>\"}" \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack (Build/Test Failed)
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\":x: *Frontend CI Failed!* ❌\n• Repo: *${{ github.repository }}*\n• Branch: *${{ github.ref_name }}*\n• Actor: *${{ github.actor }}*\n• Logs: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Logs>\"}" \
          ${{ secrets.SLACK_WEBHOOK_URL }}

  snyk-scan:
    name: Snyk Security Scan (Frontend)
    runs-on: ubuntu-latest
    needs: build-test
    timeout-minutes: 10
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Snyk scan
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: "--severity-threshold=high"

      - name: Notify Slack (Snyk Success)
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\":shield: *Frontend Snyk Scan Passed!* ✅\n• Repo: *${{ github.repository }}*\n• Branch: *${{ github.ref_name }}*\n• Run: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Report>\"}" \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack (Snyk Failed)
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\":warning: *Frontend Snyk Scan Failed!* ⚠️\nCheck logs: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>\"}" \
          ${{ secrets.SLACK_WEBHOOK_URL }}

